### PR TITLE
fix the heightmap proxy caster guy and also asteroid belt now

### LINKED ISSUE #1001: Heightmap proxy shadow caster is borked cuz lod
### What Happened?

The change to heightmaps being 2 lods caused the proxy shadow caster to not find the mesh filter because its on CubeSphere which has no mesh filter.
image
image

### What was supposed to happen?

The shadow caster should be on lod 1 (lowest) so it gets the mesh filter

### Platform

None

### Mods

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by TerrificTrifid**
## Minor features
- Added an option to use a detail for asteroid belts, instead of just procgen.
- Also added asteroid belt options for gravity and random orientation.

## Bug fixes
- Fixed the proxy shadow caster on heightmaps, so they cast shadows onto other bodies better (fixes #1001)

### CODE REVIEW

**Review by JohnCorby — APPROVED** [review]

File: NewHorizons/External/Modules/AsteroidBeltModule.cs [hunk 1]
```diff
@@ -45,13 +45,38 @@ public class AsteroidBeltModule
...
+        /// <summary>
+        /// You can use this to load a custom asset or ingame object, instead of using ProcGen. It will be scaled by "minSize" and "maxSize", so ideally it should be near a 1 meter radius.
+        /// This is either the path in the scene hierarchy of the item to copy or the path to the object in the supplied asset bundle. 
+        /// </summary>
+        public string path;
+
+        /// <summary>
+        /// Surface gravity of the asteroids.
+        /// </summary>
+        [Range(0f, double.MaxValue)]
```
Comment (xen-42) [inline NewHorizons/External/Modules/AsteroidBeltModule.cs:72]: its a float not a double

File: NewHorizons/Builder/Body/HeightMapBuilder.cs [hunk 2]
```diff
@@ -91,14 +91,14 @@ public static GameObject Make(GameObject planetGO, Sector sector, HeightMapModul
                 level2.name += "1";
 
                 LODGroup.RecalculateBounds();
+
```
Comment (xen-42) [inline NewHorizons/Builder/Body/HeightMapBuilder.cs:94]: Add a comment here saying that we only do the group stuff if LOD is on bc the only times LOD is off is for title screen and proxies

File: NewHorizons/Builder/Body/AsteroidBeltBuilder.cs [hunk 3]
```diff
@@ -62,20 +64,37 @@ public static void Make(string bodyName, PlanetConfig parentConfig, IModBehaviou
                     enabled = false
                 };
 
-                config.ProcGen = belt.procGen;
-                if (config.ProcGen == null)
+                if (belt.assetBundle != null || belt.path != null)
```
Comment (xen-42) [inline NewHorizons/Builder/Body/AsteroidBeltBuilder.cs:67]: since these are strings should probably do string.IsNullOrEmpty

File: NewHorizons/External/Modules/AsteroidBeltModule.cs [hunk 4]
```diff
@@ -45,13 +45,38 @@ public class AsteroidBeltModule
...
+        [DefaultValue(1)]
+        public float gravity = 1f;
+
+        /// <summary>
+        /// Should they be randomly oriented, or all pointing towards the center.
```
Comment (xen-42) [inline NewHorizons/External/Modules/AsteroidBeltModule.cs:77]: Since this only affects details not procgen we should say that

**Review by xen-42 — CHANGES_REQUESTED** [review]

**Review by xen-42 — APPROVED** [review]
