### PR TITLE
Repair Volumes

### LINKED ISSUE #1084: Repairables
### Feature

Add interactive "repairable" props, similar to the "satellite" nodes in the Zero-G Cave. Repairing them should set a dialogue condition and optionally reveal a ship log fact.

We could either implement this as an invisible volume and handle swapping out the broken/repaired visuals using `activationCondition`/`deactivationCondition` on details, like Dreambound does, or if we want it to be more user-friendly we can make it a prop with a separate sub-detail for each state that will be enabled/disabled automatically.

We can use Dreambound's implementation ([part 1](https://github.com/Hawkbat/OuterWildsModJam4/blob/main/GreenFlameBlade/Patches/RepairRecieverPatches.cs), [part 2](https://github.com/Hawkbat/OuterWildsModJam4/blob/main/GreenFlameBlade/Components/GenericRepairReceiver.cs)) for reference.

### Context

_No response_

### PR DESCRIPTION
**Pull request by Hawkbat**
## Minor features

- Added `repairVolumes` which act like the repairable nodes on the "satellite" in the Zero-G cave. Resolves #1084

[Examples PR](https://github.com/Outer-Wilds-New-Horizons/nh-examples/pull/59)

Also in this PR I've fixed two unrelated minor issues that were causing warnings to be flagged on every build.

### CODE REVIEW

**Comment by Hawkbat** [comment]
Functionality is entirely new so nothing that should be a concern for backwards compat. The patches to RepairReceiver are postfixes that pass-through the existing values if the component isn't a custom NH component so it should be compatible with any other patches out there.

**Review by JohnCorby — APPROVED** [review]

File: NewHorizons/Builder/Volumes/RepairVolumeBuilder.cs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+using System.Threading.Tasks;
+using UnityEngine;
+
+namespace NewHorizons.Builder.Volumes
+{
+    public static class RepairVolumeBuilder
+    {
+        public static NHRepairReceiver Make(GameObject planetGO, Sector sector, RepairVolumeInfo info)
+        {
+            // Repair receivers aren't technically volumes (no OWTriggerVolume) so we don't use the VolumeBuilder
```
Comment (xen-42) [inline NewHorizons/Builder/Volumes/RepairVolumeBuilder.cs:18]: Neither were VanishVolumes smh my head

We should log errors then if they try to set useShape to true yeah?

**Review by xen-42 — CHANGES_REQUESTED** [review]

File: NewHorizons/Builder/Volumes/RepairVolumeBuilder.cs (hunk 1 above)
Comment (Hawkbat) [reply NewHorizons/Builder/Volumes/RepairVolumeBuilder.cs:18]: ShapeBuilder will do that itself with this particular overload so we should be good there

**Review by MegaPiggy — APPROVED** [review]

**Review by xen-42 — APPROVED** [review]
